### ISSUE TITLE
build.txt (requirements file) is missing exif, lxml and rectangle-packer

### ISSUE THREAD

**Issue by dginovker** [rbreu/beeref#112]
**Describe the bug**
When trying to fix up the Flatpak build for Beeref, I hit these issues:

```
Traceback (most recent call last):
  File "beeref/__main__.py", line 30, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/view.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/fileio/__init__.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/fileio/image.py", line 24, in <module>
ModuleNotFoundError: No module named 'exif'
[3] Failed to execute script '__main__' due to unhandled exception!
```

```
Traceback (most recent call last):
  File "beeref/__main__.py", line 30, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/view.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/fileio/__init__.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/fileio/image.py", line 25, in <module>
ModuleNotFoundError: No module named 'lxml'
[3] Failed to execute script '__main__' due to unhandled exception!
```

```
Traceback (most recent call last):
  File "beeref/__main__.py", line 30, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/view.py", line 33, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "beeref/scene.py", line 23, in <module>
ModuleNotFoundError: No module named 'rpack'
[3] Failed to execute script '__main__' due to unhandled exception!
```

Both were resolved by adding `exif` and `lxml` to build.txt 

**System info**

**To Reproduce**
1. Get a barebones Linux installation
2. Try to compile Beeref

**Comment by dginovker** [comment]
Btw if you don't think this is an issue, feel free to close

**Comment by rbreu** [comment]
The requirements for BeeRef itself come from installing the beeref package itself, they are defined in pyproject.toml. So in your git clone directory, run `pip install . --upgrade`

The build.txt only holds additional requirements needed for the building tools (which is at the moment only pyinstaller). Same for all the other files in the requirements folder.
